name: AI Social Agent

on:
  schedule:
    - cron: '30 * * * *'  # runs every hour at 30 minutes past
  workflow_dispatch:      # allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install openai requests
      - name: Run script
        run: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TYPEFULLY_API_KEY: ${{ secrets.TYPEFULLY_API_KEY }}
