name: Daily Tweet Generator

on:
  schedule:
    - cron: '4 17 * * *'  # 10:34 PM IST = 17:04 UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install OpenAI
        run: pip install openai

      - name: Run Tweet Generator
        run: python3 main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Save Tweet as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tweet
          path: tweet.txt
